### ISSUE TITLE
Visa debit not accepted, can't buy a ticket!

### ISSUE THREAD

**Issue by mcintyre321** [RESTFest/2016-Edinburgh#1]
I'm trying to buy a ticket for Edinburgh but the payment popup gives me a validation error for my Visa Debit card number, although it highlights the Visa icon correctly.

I pasted the number into another validation service and it's fine. Does Visa Debit need to be enabled as an option or something?

**Comment by blongden** [comment]
I'll take a look at this for you!

**Comment by blongden** [comment]
I've just tried my own VISA debit card and it appears to be ok - worth another try?

**Comment by blongden** [comment]
Can I help any further with this?

**Comment by blongden** [comment]
I've added paypal as a payment option too if that helps!

**Comment by mcintyre321** [comment]
It worked, thanks everyone!
